version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.1.0

jobs:
  calculate-bmi:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
            pip install coverage
            pip install pytest-cov
            pip install PyYAML
            pip install python-coveralls
      - run:
          name: Run script
          command: python BMIcalculator.py 5 6 160

      - run:
          name: Run tests and generate coverage report
          command: |
            coverage run --source=BMIcalculator -m pytest t_test.py
            coverage xml

      - run:
          name: Upload to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t fcb92d05-2aa4-4d47-91fc-0622d2d6fc16 -f coverage.xml

workflows:
  run-bmi-calculator:
    jobs:
      - calculate-bmi

