version: 2.1

jobs:
  calculate-bmi:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
            pip install coverage
            pip install pytest-cov
            pip install PyYAML
            pip install python-coveralls
      - run:
          name: Run tests and coverage
          command: |
            coverage run -m pytest t_test.py
            coverage report
            coveralls
          environment:
            COVERALLS_REPO_TOKEN: c799e90bf8119fa18d388ffdb4405521f5ba17a7

workflows:
  run-bmi-calculator:
    jobs:
      - calculate-bmi


