version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.1.0

jobs:
  calculate-bmi:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
            pip install coverage
            pip install pytest-cov
            pip install PyYAML
            pip install python-coveralls
      - run:
          name: Run script
          command: python BMIcalculator.py 5 6 160

      - run:
          name: Run tests
          command: pytest --cov=BMIcalculator t_test.py

      - coveralls/coveralls-upload:
          flags: --service=circle-ci
          requires:
            - run-tests

workflows:
  run-bmi-calculator:
    jobs:
      - calculate-bmi
