version: 2.1

jobs:
  calculate-bmi:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-cov

      - run:
          name: Run script
          command: python BMIcalculator.py 5 6 160

      - run:
          name: Run tests
          command: pytest t_test.py --cov=BMIcalculator

      - run:
          name: Upload coverage report
          command: coveralls

workflows:
  run-bmi-calculator:
    jobs:
      - calculate-bmi
