version: 2.1

jobs:
  calculate-bmi:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
            pip install pytest-cov
            pip install coveralls
      - run:
          name: Run script
          command: python BMIcalculator.py 5 6 160

      - run:
          name: Run tests
          command: pytest --cov=BMIcalculator t_test.py

      - run:
          name: Generate coverage report
          command: |
            coverage report -m --fail-under=80
            coverage lcov > coverage.lcov

      - run:
          name: Upload coverage report to Coveralls
          command: coveralls
          environment:
            COVERALLS_REPO_TOKEN: c799e90bf8119fa18d388ffdb4405521f5ba17a7

workflows:
  run-bmi-calculator:
    jobs:
      - calculate-bmi

