version: 2.1

jobs:
  calculate-bmi:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run script
          command: python BMIcalculator.py 5 6 160

workflows:
  run-bmi-calculator:
    jobs:
      - calculate-bmi
